### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by luisherranz** [frontity/now-builder#17]
Update the documentation page with the new instructions:
https://docs.frontity.org/installation-and-deploy/deploy-on-now

**Comment by luisherranz** [comment]
I have updated the docs: https://docs.frontity.org/installation-and-deploy/deploy-on-now

But, @SantosGuillamot, could you please take a look? I think they are better explained this way:
https://github.com/frontity/now-builder
with "before deploy", "deploy a test" and "deploy to production".

Feel free to update the docs and the README of this repo with the best information we can provide.

**Comment by SantosGuillamot** [comment]
Yes, I think it is more clear that way, thanks! I have already updated the docs.

Maybe, once we test this #11 , we should also add the default values (for ex. cache) and how could be updated.
